import LeanFlagAlgebras.ErdosPentagon.FlagDef
import LeanFlagAlgebras.FlagAlgebra.Compute.FlagDensity
import LeanFlagAlgebras.ErdosPentagon.Densities.DensityLoader

open FlagAlgebras
open FlagAlgebras.Compute

namespace ErdosPentagon

load_density_relations "LeanFlagAlgebras/ErdosPentagon/Densities/density_5_3_2_from_4_3_2.json"

end ErdosPentagon
