import LeanFlagAlgebras.ErdosPentagon.FlagDef
import LeanFlagAlgebras.FlagAlgebra.Compute.FlagDensity
import LeanFlagAlgebras.ErdosPentagon.DensityLoader

open FlagAlgebras
open FlagAlgebras.Compute

namespace ErdosPentagon

load_density_relations "LeanFlagAlgebras/ErdosPentagon/density_5_3_2_from_4_3_2.json"

end ErdosPentagon
