import LeanFlagAlgebras.ErdosPentagon.MulLoader

open FlagAlgebras Forbid
open FlagAlgebras.Compute

namespace ErdosPentagon

load_triangle_density_theorems "LeanFlagAlgebras/ErdosPentagon/Densities/graphs_5_triangle_free_indices.json"

load_flag_pair_density_theorems "LeanFlagAlgebras/ErdosPentagon/Densities/density_5_3_0_from_4_3_0.json"
-- load_triangle_free_classification "LeanFlagAlgebras/ErdosPentagon/Densities/density_5_3_0_from_4_3_0.json"
load_mul_theorems "LeanFlagAlgebras/ErdosPentagon/Densities/density_5_3_0_from_4_3_0.json"

load_flag_pair_density_theorems "LeanFlagAlgebras/ErdosPentagon/Densities/density_5_3_1_from_4_3_1.json"
-- load_triangle_free_classification "LeanFlagAlgebras/ErdosPentagon/Densities/density_5_3_1_from_4_3_1.json"
load_mul_theorems "LeanFlagAlgebras/ErdosPentagon/Densities/density_5_3_1_from_4_3_1.json"

load_flag_pair_density_theorems "LeanFlagAlgebras/ErdosPentagon/Densities/density_5_3_2_from_4_3_2.json"
-- load_triangle_free_classification "LeanFlagAlgebras/ErdosPentagon/Densities/density_5_3_2_from_4_3_2.json"
load_mul_theorems "LeanFlagAlgebras/ErdosPentagon/Densities/density_5_3_2_from_4_3_2.json"

#print flagMul_FlagAlgebra_4_3_2_0_FlagAlgebra_4_3_2_0

end ErdosPentagon
