-- Forbid-free analogue of `Flagmatic/Mantel.lean` (Mantel's theorem: a triangle-free
-- graph has edge density ≤ 1/2). This version exercises the forbid-free generation
-- and bridges end-to-end:
--
--   * `generate_forbid_free_empty_typed_flags` / `generate_forbid_free_flags` emit only
--     the K3-free flags and their filtered-completeness lemma (`flagSetHfree_…_eq`);
--   * `generate_forbid_free_mul_theorems` proves the products `=[K3]` over the
--     forbid-free host set rather than the full `flagSet`;
--   * the objective is expanded with `basisVector_quot_forbidEq_sum` rewritten onto
--     `flagSetHfree` directly (no full expansion + manual triangle-term drop);
--   * the unit is expanded with `expand_one_hfree_at`.
--
-- At host size 3 every flag is already generated by `FlagDef`, so there is no
-- generation saving here; the point is to validate that the forbid-free bridges
-- compose into a complete density-bound proof. The savings appear at host sizes
-- `FlagDef` does not generate (n ≥ 6, empty-typed).
import LeanFlagAlgebras.Flags.FlagDef
import LeanFlagAlgebras.Flags.ForbidFreeGenerator
import LeanFlagAlgebras.Flags.Densities.MulThmGenerator
import LeanFlagAlgebras.Flags.Densities.DensityThmGenerator
import LeanFlagAlgebras.API.Basic
import LeanFlagAlgebras.API.FlagMulReduce
import LeanFlagAlgebras.API.FlagSumSort
import LeanFlagAlgebras.API.Matrix.PosSemiDef
import LeanFlagAlgebras.API.FlagExpand
import LeanFlagAlgebras.FlagAlgebra.Compute.FlagDensity
import LeanFlagAlgebras.Forbid.CommonGraphs

open FlagAlgebras Forbid FlagAlgebras.API
open SimpleGraph Matrix
open FlagAlgebras.Compute

namespace MantelHfree

generate_forbid_density_theorems 3 K3
generate_flag_pair_density_theorems 2 3 1 0 K3
-- Forbid-free: generate only the K3-free flags + completeness, then the forbid-free
-- multiplication theorems (proved over `flagSetHfree`, not the full `flagSet`).
generate_forbid_free_empty_typed_flags 3 K3
generate_forbid_free_flags 1 0 3 K3
generate_forbid_free_mul_theorems 2 3 1 0 K3

/-- SDP certificate matrix for block 1 (rational, 2×2), paired with `v`. -/
def M : Matrix (Fin 2) (Fin 2) ℚ :=
  !![(1 / 2 : ℚ), (-1 / 2 : ℚ);
    (-1 / 2 : ℚ), (1 / 2 : ℚ)]
noncomputable def M_real : Matrix (Fin 2) (Fin 2) ℝ :=
  ratMatrixToReal M
def dM : Fin 2 → ℚ :=
  ![(1 / 2 : ℚ), 0]
def LM : Matrix (Fin 2) (Fin 2) ℚ :=
  !![(1 : ℚ), 0;
    (-1 : ℚ), (1 : ℚ)]
lemma dM_nonneg (i : Fin 2) : 0 ≤ dM i := by
  fin_cases i <;> norm_num [dM]
lemma M_eq_LDL : M = LM * Matrix.diagonal dM * LMᵀ := by
  decide +kernel
theorem M_posSemidef : M.PosSemidef := by
  exact posSemidef_of_LDLt dM_nonneg M_eq_LDL
lemma dM_real_nonneg (i : Fin 2) : 0 ≤ (dM i : ℝ) := by
  exact_mod_cast dM_nonneg i
lemma M_real_eq_LDL :
    M_real = (ratMatrixToReal LM * Matrix.diagonal (fun i => (dM i : ℝ))) * (ratMatrixToReal LM)ᵀ := by
  calc
    M_real = ratMatrixToReal (LM * Matrix.diagonal dM * LMᵀ) := by
      simp [M_real, ratMatrixToReal, M_eq_LDL]
    _ = (ratMatrixToReal LM * Matrix.diagonal (fun i => (dM i : ℝ))) * (ratMatrixToReal LM)ᵀ := by
      simp [ratMatrixToReal, Matrix.map_mul_ratCast, Matrix.transpose_map, mul_assoc]
/-- `M_real` is positive semidefinite (via its real LDLᵀ factorization). -/
theorem M_real_posSemidef : M_real.PosSemidef := by
  exact posSemidef_of_LDLt_real dM_real_nonneg M_real_eq_LDL

/-- Label type for block 1 (flagmatic type '1:'). -/
def σ : FlagType (Fin 1) := FlagType_1_0
/-- Flag vector for block 1: the 2 σ-type 2-vertex flags paired with M. -/
noncomputable def v : FlagAlgebraVec σ 2 := ![
  FlagAlgebra_2_1_0_0,
  FlagAlgebra_2_1_0_1
]

set_option maxHeartbeats 0
set_option maxRecDepth 1500

-- `flagDensity₁` evaluation table for the K3-free 3-vertex flags (used by the
-- forbid-free objective expansion below).
@[simp]
private theorem auto_flagDensity1_2_0_0_1_3_0_0_0
    : flagDensity₁ Flag_2_0_0_1 Flag_3_0_0_0 = 0 := by
  dsimp [Flag_2_0_0_1, Flag_3_0_0_0]
  rw [flagDensity₁_eq_sym2EmptyTypeFlagDensity₁]
  native_decide

@[simp]
private theorem auto_flagDensity1_2_0_0_1_3_0_0_1
    : flagDensity₁ Flag_2_0_0_1 Flag_3_0_0_1 = 1 / 3 := by
  dsimp [Flag_2_0_0_1, Flag_3_0_0_1]
  rw [flagDensity₁_eq_sym2EmptyTypeFlagDensity₁]
  native_decide

@[simp]
private theorem auto_flagDensity1_2_0_0_1_3_0_0_2
    : flagDensity₁ Flag_2_0_0_1 Flag_3_0_0_2 = 2 / 3 := by
  dsimp [Flag_2_0_0_1, Flag_3_0_0_2]
  rw [flagDensity₁_eq_sym2EmptyTypeFlagDensity₁]
  native_decide

/-- Forbid-free expansion of the objective: `FlagAlgebra_2_0_0_1` is expanded directly
over the K3-free 3-vertex flags via `basisVector_quot_forbidEq_sum` rewritten onto
`flagSetHfree_3_0_0_K3` (no full `flagSet`, no manual triangle-term drop). -/
lemma mantel_flagAlgebra_expand_under_forbid
    : FlagAlgebra_2_0_0_1 =[K3.toFinFlag] (1 / 3 : ℝ) • FlagAlgebra_3_0_0_1 + (2 / 3 : ℝ) • FlagAlgebra_3_0_0_2
  := by
  apply Forbid.forbidEq_trans
    (Forbid.basisVector_quot_forbidEq_sum K3.toFinFlag ⟨2, Flag_2_0_0_1⟩ 3 (by decide))
  rw [Finset.sum_congr (s₂ := flagSetHfree_3_0_0_K3)
        (by rw [flagSetHfree_3_0_0_K3_eq]; try congr 1) (fun _ _ => rfl)]
  simp only [Finset.sum_eq_multiset_sum, flagSetHfree_3_0_0_K3_val_eq]
  simp
  exact Forbid.forbidEq_refl K3.toFinFlag _

/-- **Mantel's theorem (forbid-free formalization).**
A `K3`-free graph has edge density at most `1/2`. -/
theorem mantel_flagAlgebra
    : FlagAlgebra_2_0_0_1 ≤[K3.toFinFlag] (1 / 2 : ℝ) • (1 : FlagAlgebra ∅ₜ)
  := by
  have quadraticForm_trans : FlagAlgebra_2_0_0_1 ≤[K3.toFinFlag]
            FlagAlgebra_2_0_0_1 + ⟦flagQuadraticForm M_real v⟧₀
    := by
    apply forbidLE_add_QuadraticForm M_real M_real_posSemidef v
    exact forbidLE_refl K3.toFinFlag FlagAlgebra_2_0_0_1
  apply forbidLE_trans quadraticForm_trans
  apply forbidLE_trans_forbidEq_right ?_  (forbidEq_smul (forbidEq_symm (one_forbidEq_forbidExpand_one K3.toFinFlag 3)))
  rw [forbidLE_rw_left_add_right mantel_flagAlgebra_expand_under_forbid]

  simp [flagQuadraticForm, v, M_real, ratMatrixToReal, M, Fin.sum_univ_two, add_assoc]
  reduce_downward_flagmul

  expand_one_hfree_at 3 K3

  simp [smul_smul, downward_add, downward_smul]
  flagsum_ac_sort_rhs_pipeline

  apply forbidLE_of_le
  flag_nonneg

end MantelHfree
