import «LeanFlagAlgebras».Differential.DeleteEdge
import «LeanFlagAlgebras».FlagAlgebra.RandomHom
import Mathlib.Topology.ContinuousMap.StoneWeierstrass

/-! # Moments of the random ensemble (the role of Razborov's Theorem 3.12)

The random extension measure `ℙ[φ₀]` of `FlagAlgebra.RandomHom` is known only
through its defining moments `∫ φ, φ(x) ∂ℙ[φ₀] = φ₀(⟦x⟧_σ)/φ₀(⟦1⟧_σ)` for
`x ∈ A^σ`. This file upgrades that description to a workable calculus:

* `densityEvalFun v` — the linear evaluation `a ↦ ∑_F v_F · a_F` of a formal
  flag vector on the density-profile space; it agrees with `φ ⟦v⟧` at
  homomorphism points and with `p^X(v)` at the density points of finite flags;
* `FinFlag.integral_toMeasure_eq_sum` — integrals against the random-labelling
  measure of a finite flag are weighted sums over its label extensions;
* `coordAlgebra σ` — the subalgebra of `C(FlagDensitySpace σ, ℝ)` generated by
  the coordinate evaluations; it separates points, so by **Stone–Weierstrass**
  it is uniformly dense (`exists_coordAlgebra_near`);
* `coordAlgebra_approx` — every `g ∈ coordAlgebra σ` agrees with the
  evaluation of some formal vector `v_g` *exactly* at homomorphism points and
  up to `C/n` at the density points of `n`-vertex flags (the chain rule and
  the pair-density approximation `flagListDensity₂_prod_approx` make products
  collapse asymptotically);
* `tendsto_integral_coordAlgebra` / `integral_probMeasure_coordAlgebra` —
  consequently, along **any** flag sequence converging to `φ₀` the empirical
  integrals of `g` converge to `∫ g ∂ℙ[φ₀]`.

Together with Stone–Weierstrass this says exactly that the empirical measures
of any convergent flag sequence converge weakly to `ℙ[φ₀]` — the content of
Razborov's Theorem 3.12 in the form needed for the variational principles. -/

open MeasureTheory Filter
open scoped Topology

namespace FlagAlgebras
namespace Differential

open Finset
open Classical

variable {n₀ : ℕ} {σ : FlagType (Fin n₀)}

/-! ## Linear evaluation on the density-profile space -/

/-- The linear evaluation of a formal flag vector at a density profile:
`a ↦ ∑_F v_F · a_F`. -/
noncomputable def densityEvalFun (v : FlagVector σ) : FlagDensitySpace σ → ℝ :=
  fun a => ∑ F ∈ v.support, v F * a F

theorem continuous_densityEvalFun (v : FlagVector σ)
    : Continuous (densityEvalFun v)
  := by
  apply continuous_finset_sum
  intro F _
  exact Continuous.mul continuous_const (FinFlag.continuous F)

theorem measurable_densityEvalFun (v : FlagVector σ)
    : Measurable (densityEvalFun v)
  := by
  apply Finset.measurable_sum
  intro F _
  exact (flagDensitySpace_eval_measurable F).const_mul (v F)

theorem abs_densityEvalFun_le (v : FlagVector σ) (a : FlagDensitySpace σ)
    : |densityEvalFun v a| ≤ ∑ F ∈ v.support, |v F|
  := by
  refine le_trans (Finset.abs_sum_le_sum_abs _ _) (Finset.sum_le_sum ?_)
  intro F _
  rw [abs_mul]
  calc |v F| * |a F| ≤ |v F| * 1 :=
        mul_le_mul_of_nonneg_left (flagDensitySpace_abs_le_one a F) (abs_nonneg _)
    _ = |v F| := mul_one _

/-- At the density point of a finite flag, `densityEvalFun` is the density
evaluation `p^X(v)`. -/
theorem densityEvalFun_emp {ℓ : ℕ} (v : FlagVector σ) (X : FlagWithSize σ ℓ)
    : densityEvalFun v (funFromFlagWithSizeToFlagDensitySpace σ ℓ X) = densityEval v ⟨ℓ, X⟩
  := by
  dsimp only [densityEvalFun, densityEval, linearExtension]
  apply Finset.sum_congr rfl
  intro F _
  rw [smul_eq_mul]
  rfl

/-- At a homomorphism point, `densityEvalFun` is the homomorphism value. -/
theorem densityEvalFun_hom (v : FlagVector σ) (φ : PositiveHom σ)
    : densityEvalFun v φ.coe = φ ⟦v⟧
  := by
  conv_rhs => rw [flagVector_eq_sum_basisVector v]
  rw [sum_quot, PositiveHom.map_sum]
  apply Finset.sum_congr rfl
  intro F _
  rw [smul_quot, PositiveHom.map_smul, ← PositiveHom.coe_flag]

theorem densityEvalFun_toPosHom (v : FlagVector σ) (φ : PositiveHomSpace σ)
    : densityEvalFun v φ.val = (PositiveHomSpace.toPosHom φ) ⟦v⟧
  := by
  have h := Classical.choose_spec φ.property
  rw [← densityEvalFun_hom v (PositiveHomSpace.toPosHom φ)]
  show densityEvalFun v φ.val = densityEvalFun v (PositiveHomSpace.toPosHom φ).coe
  rw [show (PositiveHomSpace.toPosHom φ).coe = φ.val from h]

/-! ## Integrals against the random-labelling measure of a finite flag -/

/-- Integrals against `G.toMeasure` are weighted sums over label extensions. -/
theorem FinFlag.integral_toMeasure_eq_sum
    (G : FinFlag ∅ₜ) (hG : flagDensity₁ σ.toEmptyTypeFlag G.2 > 0)
    (f : FlagDensitySpace σ → ℝ) (hf : Integrable f (G.toMeasure hG))
    : ∫ a, f a ∂(G.toMeasure hG)
      = ∑ F' ∈ labelExtensions G.2 σ,
          ((downwardNormalizingFactor F' : ℝ)
            / ∑ F'' ∈ labelExtensions G.2 σ, (downwardNormalizingFactor F'' : ℝ))
          * f (funFromFlagWithSizeToFlagDensitySpace σ G.1 F')
  := by
  dsimp only [FinFlag.toMeasure] at hf ⊢
  rw [PMF.integral_eq_tsum _ _ hf]
  dsimp only [FinFlag.toPMF]
  simp only [PMF.ofFinset_apply, smul_eq_mul]
  simp_rw [apply_ite ENNReal.toReal]
  conv =>
    lhs; congr; ext a; lhs; arg 2
    rw [ENNReal.toReal_ofReal (by apply div_nonneg; all_goals {
      apply Finset.sum_nonneg
      intros
      rw [Rat.cast_nonneg]
      exact downwardNormalizingFactor_nonneg _
    })]
  simp only [ENNReal.toReal_zero, ite_mul, zero_mul]
  let L := labelExtensions G.2 σ
  let g := funFromFlagWithSizeToFlagDensitySpace σ G.1
  let dnf_sum := fun a ↦ ∑ G' ∈ L with g G' = a, (downwardNormalizingFactor G' : ℝ)
  let dnf_total := ∑ F' ∈ L, (downwardNormalizingFactor F' : ℝ)
  calc
    _ = ∑ a ∈ (g '' L).toFinset, dnf_sum a / dnf_total * f a := by
      nth_rw 2 [← tsum_ite_eq_sum]
      congr!
    _ = ∑ G' ∈ L, (downwardNormalizingFactor G' : ℝ) * f (g G') / dnf_total := by
      rw [Set.toFinset_image, Finset.toFinset_coe]
      apply Finset.sum_image'
      intro G' hG'
      rw [mul_comm, mul_div, ← Finset.sum_div]
      congr
      rw [mul_comm, Finset.sum_mul]
      apply Finset.sum_congr rfl
      intro G'' hG''
      simp only [Finset.mem_filter] at hG''
      rw [hG''.2]
    _ = _ := by
      apply Finset.sum_congr rfl
      intro G' _
      rw [div_mul_eq_mul_div, mul_comm]

theorem sum_labelExtensions_weight_eq_one
    (G : FinFlag ∅ₜ) (hG : flagDensity₁ σ.toEmptyTypeFlag G.2 > 0)
    : ∑ F' ∈ labelExtensions G.2 σ,
        ((downwardNormalizingFactor F' : ℝ)
          / ∑ F'' ∈ labelExtensions G.2 σ, (downwardNormalizingFactor F'' : ℝ)) = 1
  := by
  rw [← Finset.sum_div]
  apply div_self
  apply ne_of_gt
  apply Finset.sum_pos
  · intro F' _
    simp only [Rat.cast_pos]
    exact downwardNormalizingFactor_pos F'
  · exact labelExtensions_nonempty hG

/-- If two integrands are within `c` of each other at every label-extension
point, their integrals differ by at most `c`. -/
theorem FinFlag.abs_integral_toMeasure_sub_le
    (G : FinFlag ∅ₜ) (hG : flagDensity₁ σ.toEmptyTypeFlag G.2 > 0)
    (f g : FlagDensitySpace σ → ℝ)
    (hf : Integrable f (G.toMeasure hG)) (hg : Integrable g (G.toMeasure hG))
    {c : ℝ} (hc : 0 ≤ c)
    (hb : ∀ F' ∈ labelExtensions G.2 σ,
      |f (funFromFlagWithSizeToFlagDensitySpace σ G.1 F')
        - g (funFromFlagWithSizeToFlagDensitySpace σ G.1 F')| ≤ c)
    : |(∫ a, f a ∂(G.toMeasure hG)) - ∫ a, g a ∂(G.toMeasure hG)| ≤ c
  := by
  rw [FinFlag.integral_toMeasure_eq_sum G hG f hf, FinFlag.integral_toMeasure_eq_sum G hG g hg,
    ← Finset.sum_sub_distrib]
  have hw : ∀ F' ∈ labelExtensions G.2 σ,
      (0 : ℝ) ≤ (downwardNormalizingFactor F' : ℝ)
        / ∑ F'' ∈ labelExtensions G.2 σ, (downwardNormalizingFactor F'' : ℝ) := by
    intro F' _
    apply div_nonneg
    · simp only [Rat.cast_nonneg]
      exact downwardNormalizingFactor_nonneg F'
    · apply Finset.sum_nonneg
      intros
      simp only [Rat.cast_nonneg]
      exact downwardNormalizingFactor_nonneg _
  calc |∑ F' ∈ labelExtensions G.2 σ,
        (((downwardNormalizingFactor F' : ℝ) / _) * f _ - ((downwardNormalizingFactor F' : ℝ) / _) * g _)|
      ≤ ∑ F' ∈ labelExtensions G.2 σ,
        |((downwardNormalizingFactor F' : ℝ) / _) * f _ - ((downwardNormalizingFactor F' : ℝ) / _) * g _| :=
        Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ F' ∈ labelExtensions G.2 σ,
        ((downwardNormalizingFactor F' : ℝ)
          / ∑ F'' ∈ labelExtensions G.2 σ, (downwardNormalizingFactor F'' : ℝ)) * c := by
        apply Finset.sum_le_sum
        intro F' hF'
        rw [← mul_sub, abs_mul, abs_of_nonneg (hw F' hF')]
        exact mul_le_mul_of_nonneg_left (hb F' hF') (hw F' hF')
    _ = c := by
        rw [← Finset.sum_mul, sum_labelExtensions_weight_eq_one G hG, one_mul]

/-- Integrability of any pointwise-bounded measurable function against a
probability measure (convenience wrapper). -/
theorem integrable_of_bounded {X : Type*} [MeasurableSpace X] {μ : Measure X}
    [IsProbabilityMeasure μ] {f : X → ℝ} (hm : Measurable f) (B : ℝ) (hB : ∀ a, |f a| ≤ B)
    : Integrable f μ
  := by
  apply Integrable.of_bound hm.aestronglyMeasurable B
  apply ae_of_all
  intro a
  rw [Real.norm_eq_abs]
  exact hB a

/-! ## The coordinate algebra and Stone–Weierstrass -/

/-- The coordinate evaluation as a continuous map on the density space. -/
noncomputable def coordCM (F : FinFlag σ) : C(FlagDensitySpace σ, ℝ) :=
  ⟨fun a => a F, FinFlag.continuous F⟩

/-- The subalgebra of `C(FlagDensitySpace σ, ℝ)` generated by the coordinate
evaluations. -/
noncomputable def coordAlgebra (σ : FlagType (Fin n₀)) : Subalgebra ℝ C(FlagDensitySpace σ, ℝ) :=
  Algebra.adjoin ℝ (Set.range (coordCM (σ := σ)))

theorem coordAlgebra_separatesPoints : (coordAlgebra σ).SeparatesPoints := by
  intro a b hab
  have hex : ∃ F, a F ≠ b F := by
    by_contra hc
    push_neg at hc
    exact hab (DFunLike.coe_injective (funext hc))
  obtain ⟨F, hF⟩ := hex
  exact ⟨coordCM F, ⟨coordCM F, Algebra.subset_adjoin (Set.mem_range_self F), rfl⟩, hF⟩

/-- **Stone–Weierstrass** for the density space: every continuous function is
uniformly approximated by elements of the coordinate algebra. -/
theorem exists_coordAlgebra_near (h : FlagDensitySpace σ → ℝ) (hc : Continuous h)
    {ε : ℝ} (hε : 0 < ε)
    : ∃ g ∈ coordAlgebra σ, ∀ a, |g a - h a| < ε
  := by
  obtain ⟨g, hg⟩ := ContinuousMap.exists_mem_subalgebra_near_continuous_of_separatesPoints
    (coordAlgebra σ) coordAlgebra_separatesPoints h hc ε hε
  refine ⟨g.val, g.property, ?_⟩
  intro a
  have := hg a
  rwa [Real.norm_eq_abs] at this

/-! ## Products collapse asymptotically -/

/-- On hosts large enough, the evaluation of a flag product is the pair
density (the chain rule). -/
theorem densityEval_flagMul_eq (F G : FinFlag σ) {n : ℕ} (X : FlagWithSize σ n)
    (hn : F.1 + G.1 ≤ n + n₀)
    : densityEval (flagMul F G) ⟨n, X⟩ = (flagDensity₂ F.2 G.2 X : ℝ)
  := by
  have hF := finFlag_size_ge_n₀ F
  have hG := finFlag_size_ge_n₀ G
  dsimp only [flagMul, flagMulWithSize]
  rw [densityEval_sum]
  simp_rw [rat_smul_eq_real_smul, densityEval_smul, densityEval_basisVector]
  rw [density_chain_rule₂₁ (F.1 + G.1 - n₀) F.2 G.2 X hF hG (by omega) (by omega)]
  push_cast
  rfl

/-- The pair-density approximation, in evaluation form: the evaluation of a
flag product differs from the product of evaluations by `O(1/n)` at the
density point of any `n`-vertex flag. -/
theorem densityEval_flagMul_approx (F G : FinFlag σ)
    : ∃ c : ℝ, 0 ≤ c ∧ ∀ (n : ℕ) (X : FlagWithSize σ n), 1 ≤ n →
        |densityEval (flagMul F G) ⟨n, X⟩
          - (flagDensity₁ F.2 X : ℝ) * (flagDensity₁ G.2 X : ℝ)| ≤ c / n
  := by
  obtain ⟨c₀, hc₀, hc⟩ := flagListDensity₂_prod_approx F.2 G.2
  set A : ℝ := ∑ H ∈ (flagMul F G).support, |(flagMul F G) H| with hA
  have hA0 : 0 ≤ A := Finset.sum_nonneg (fun _ _ => abs_nonneg _)
  refine ⟨max (c₀ : ℝ) ((A + 1) * (F.1 + G.1)), le_max_of_le_left (by exact_mod_cast hc₀), ?_⟩
  intro n X hn
  by_cases hsize : F.1 + G.1 ≤ n + n₀
  · rw [densityEval_flagMul_eq F G X hsize]
    have h1 := hc X
    have h2 : (Quotient.out X).size = n := by
      simp only [LabeledGraph.size, Fintype.card_fin]
    rw [h2] at h1
    have h3 : |(flagDensity₂ F.2 G.2 X : ℝ) - (flagDensity₁ F.2 X : ℝ) * (flagDensity₁ G.2 X : ℝ)|
        ≤ (c₀ : ℝ) / n := by
      have h4 : ((|flagDensity₂ F.2 G.2 X - flagDensity₁ F.2 X * flagDensity₁ G.2 X| : ℚ) : ℝ)
          ≤ ((c₀ / n : ℚ) : ℝ) := by exact_mod_cast h1
      push_cast at h4
      exact h4
    refine le_trans h3 ?_
    apply div_le_div_of_nonneg_right ?_ (by positivity)
    · exact le_max_left _ _
  · have h1 : |densityEval (flagMul F G) ⟨n, X⟩| ≤ A := abs_densityEval_le _ _
    have h2 : |(flagDensity₁ F.2 X : ℝ) * (flagDensity₁ G.2 X : ℝ)| ≤ 1 := by
      rw [abs_mul]
      have hF1 : |(flagDensity₁ F.2 X : ℝ)| ≤ 1 := by
        rw [abs_le]
        constructor
        · have := flagListDensity₁_ge_zero F.2 X
          have : (0 : ℝ) ≤ (flagDensity₁ F.2 X : ℝ) := by exact_mod_cast this
          linarith
        · exact_mod_cast flagListDensity₁_le_one F.2 X
      have hG1 : |(flagDensity₁ G.2 X : ℝ)| ≤ 1 := by
        rw [abs_le]
        constructor
        · have := flagListDensity₁_ge_zero G.2 X
          have : (0 : ℝ) ≤ (flagDensity₁ G.2 X : ℝ) := by exact_mod_cast this
          linarith
        · exact_mod_cast flagListDensity₁_le_one G.2 X
      calc |(flagDensity₁ F.2 X : ℝ)| * |(flagDensity₁ G.2 X : ℝ)| ≤ 1 * 1 :=
            mul_le_mul hF1 hG1 (abs_nonneg _) zero_le_one
        _ = 1 := one_mul 1
    have h3 : |densityEval (flagMul F G) ⟨n, X⟩
        - (flagDensity₁ F.2 X : ℝ) * (flagDensity₁ G.2 X : ℝ)| ≤ A + 1 :=
      le_trans (abs_sub _ _) (add_le_add h1 h2)
    refine le_trans h3 (le_trans ?_ (div_le_div_of_nonneg_right (le_max_right _ _) (by positivity)))
    rw [le_div_iff₀ (by positivity : (0 : ℝ) < n)]
    have h5 : (n : ℝ) ≤ (F.1 + G.1 : ℕ) := by
      have : n < F.1 + G.1 := by omega
      exact_mod_cast le_of_lt this
    calc (A + 1) * (n : ℝ) ≤ (A + 1) * ((F.1 + G.1 : ℕ) : ℝ) :=
          mul_le_mul_of_nonneg_left h5 (by linarith)
      _ = (A + 1) * ((F.1 : ℝ) + (G.1 : ℝ)) := by push_cast; ring

/-- The evaluation of a product of formal vectors differs from the product of
evaluations by `O(1/n)` at the density points of `n`-vertex flags. -/
theorem densityEval_mul_approx (v w : FlagVector σ)
    : ∃ c : ℝ, 0 ≤ c ∧ ∀ (n : ℕ) (X : FlagWithSize σ n), 1 ≤ n →
        |densityEval (v * w) ⟨n, X⟩ - densityEval v ⟨n, X⟩ * densityEval w ⟨n, X⟩| ≤ c / n
  := by
  have hchoice : ∀ FG : FinFlag σ × FinFlag σ, ∃ c : ℝ, 0 ≤ c ∧
      ∀ (n : ℕ) (X : FlagWithSize σ n), 1 ≤ n →
        |densityEval (flagMul FG.1 FG.2) ⟨n, X⟩
          - (flagDensity₁ FG.1.2 X : ℝ) * (flagDensity₁ FG.2.2 X : ℝ)| ≤ c / n :=
    fun FG => densityEval_flagMul_approx FG.1 FG.2
  choose c hc0 hc using hchoice
  refine ⟨∑ F ∈ v.support, ∑ G ∈ w.support, |v F * w G| * c (F, G), ?_, ?_⟩
  · apply Finset.sum_nonneg
    intro F _
    apply Finset.sum_nonneg
    intro G _
    exact mul_nonneg (abs_nonneg _) (hc0 (F, G))
  intro n X hn
  have hexp : densityEval (v * w) ⟨n, X⟩
      = ∑ F ∈ v.support, ∑ G ∈ w.support, (v F * w G) * densityEval (flagMul F G) ⟨n, X⟩ := by
    rw [flagVector_mul_eq_nested_sum, densityEval_sum]
    apply Finset.sum_congr rfl
    intro F _
    rw [densityEval_sum]
    apply Finset.sum_congr rfl
    intro G _
    rw [densityEval_smul]
  have hprod : densityEval v ⟨n, X⟩ * densityEval w ⟨n, X⟩
      = ∑ F ∈ v.support, ∑ G ∈ w.support,
          (v F * w G) * ((flagDensity₁ F.2 X : ℝ) * (flagDensity₁ G.2 X : ℝ)) := by
    dsimp only [densityEval, linearExtension]
    rw [Finset.sum_mul]
    apply Finset.sum_congr rfl
    intro F _
    rw [Finset.mul_sum]
    apply Finset.sum_congr rfl
    intro G _
    simp only [smul_eq_mul]
    ring
  rw [hexp, hprod, ← Finset.sum_sub_distrib]
  calc |∑ F ∈ v.support, (∑ G ∈ w.support, (v F * w G) * densityEval (flagMul F G) ⟨n, X⟩
        - ∑ G ∈ w.support, (v F * w G) * ((flagDensity₁ F.2 X : ℝ) * (flagDensity₁ G.2 X : ℝ)))|
      ≤ ∑ F ∈ v.support, |∑ G ∈ w.support, (v F * w G) * densityEval (flagMul F G) ⟨n, X⟩
        - ∑ G ∈ w.support, (v F * w G) * ((flagDensity₁ F.2 X : ℝ) * (flagDensity₁ G.2 X : ℝ))| :=
        Finset.abs_sum_le_sum_abs _ _
    _ ≤ ∑ F ∈ v.support, ∑ G ∈ w.support, |v F * w G| * (c (F, G) / n) := by
        apply Finset.sum_le_sum
        intro F _
        rw [← Finset.sum_sub_distrib]
        refine le_trans (Finset.abs_sum_le_sum_abs _ _) (Finset.sum_le_sum ?_)
        intro G _
        rw [← mul_sub, abs_mul]
        exact mul_le_mul_of_nonneg_left (hc (F, G) n X hn) (abs_nonneg _)
    _ = (∑ F ∈ v.support, ∑ G ∈ w.support, |v F * w G| * c (F, G)) / n := by
        rw [Finset.sum_div]
        apply Finset.sum_congr rfl
        intro F _
        rw [Finset.sum_div]
        apply Finset.sum_congr rfl
        intro G _
        rw [mul_div_assoc]

/-! ## Every coordinate polynomial is asymptotically an algebra evaluation -/

/-- **The moment dictionary.** Every element `g` of the coordinate algebra is
represented by a formal flag vector `v`: exactly at homomorphism points, and
up to `C/n` at the density points of `n`-vertex flags. (Products collapse by
the pair-density approximation; this is the algebraic heart of Razborov's
Theorem 3.12.) -/
theorem coordAlgebra_approx {g : C(FlagDensitySpace σ, ℝ)} (hg : g ∈ coordAlgebra σ)
    : ∃ (v : FlagVector σ) (C : ℝ), 0 ≤ C ∧ Measurable ⇑g ∧
        (∀ φ : PositiveHom σ, g φ.coe = φ ⟦v⟧) ∧
        (∀ (n : ℕ) (X : FlagWithSize σ n), 1 ≤ n →
          |g (funFromFlagWithSizeToFlagDensitySpace σ n X) - densityEval v ⟨n, X⟩| ≤ C / n)
  := by
  induction hg using Algebra.adjoin_induction with
  | mem x hx =>
    obtain ⟨F, rfl⟩ := hx
    refine ⟨basisVector F, 0, le_refl 0, flagDensitySpace_eval_measurable F, ?_, ?_⟩
    · intro φ
      show φ.coe F = φ ⟦basisVector F⟧
      exact PositiveHom.coe_flag φ F
    · intro n X hn
      show |funFromFlagWithSizeToFlagDensitySpace σ n X F - densityEval (basisVector F) ⟨n, X⟩| ≤ 0 / n
      rw [densityEval_basisVector]
      have h1 : funFromFlagWithSizeToFlagDensitySpace σ n X F = (flagDensity₁ F.2 X : ℝ) := rfl
      rw [h1, sub_self, abs_zero, zero_div]
  | algebraMap r =>
    have hcoe : ⇑((algebraMap ℝ C(FlagDensitySpace σ, ℝ)) r) = fun _ => r := rfl
    refine ⟨r • basisVector 1, 0, le_refl 0, ?_, ?_, ?_⟩
    · rw [hcoe]
      exact measurable_const
    · intro φ
      show ((algebraMap ℝ C(FlagDensitySpace σ, ℝ)) r) φ.coe = φ ⟦r • basisVector 1⟧
      rw [hcoe]
      show r = φ ⟦r • basisVector 1⟧
      rw [smul_quot, PositiveHom.map_smul]
      have h1 : (⟦basisVector 1⟧ : FlagAlgebra σ) = 1 := rfl
      rw [h1, PositiveHom.map_one, mul_one]
    · intro n X hn
      show |((algebraMap ℝ C(FlagDensitySpace σ, ℝ)) r) _ - densityEval (r • basisVector 1) ⟨n, X⟩| ≤ 0 / n
      rw [hcoe]
      show |r - densityEval (r • basisVector 1) ⟨n, X⟩| ≤ 0 / n
      rw [densityEval_smul, densityEval_basisVector, flagDensity_one]
      norm_num
  | add x y hx hy ihx ihy =>
    obtain ⟨v₁, C₁, hC₁, hm₁, hhom₁, happ₁⟩ := ihx
    obtain ⟨v₂, C₂, hC₂, hm₂, hhom₂, happ₂⟩ := ihy
    refine ⟨v₁ + v₂, C₁ + C₂, by linarith, ?_, ?_, ?_⟩
    · show Measurable fun a => x a + y a
      exact hm₁.add hm₂
    · intro φ
      show x φ.coe + y φ.coe = φ ⟦v₁ + v₂⟧
      rw [add_quot, PositiveHom.map_add, hhom₁ φ, hhom₂ φ]
    · intro n X hn
      show |(x _ + y _) - densityEval (v₁ + v₂) ⟨n, X⟩| ≤ (C₁ + C₂) / n
      rw [densityEval_add]
      set aX := funFromFlagWithSizeToFlagDensitySpace σ n X with haX
      have h1 : x aX + y aX - (densityEval v₁ ⟨n, X⟩ + densityEval v₂ ⟨n, X⟩)
          = (x aX - densityEval v₁ ⟨n, X⟩) + (y aX - densityEval v₂ ⟨n, X⟩) := by ring
      rw [h1]
      calc |(x aX - densityEval v₁ ⟨n, X⟩) + (y aX - densityEval v₂ ⟨n, X⟩)|
          ≤ |x aX - densityEval v₁ ⟨n, X⟩| + |y aX - densityEval v₂ ⟨n, X⟩| := abs_add_le _ _
        _ ≤ C₁ / n + C₂ / n := add_le_add (happ₁ n X hn) (happ₂ n X hn)
        _ = (C₁ + C₂) / n := (add_div _ _ _).symm
  | mul x y hx hy ihx ihy =>
    obtain ⟨v₁, C₁, hC₁, hm₁, hhom₁, happ₁⟩ := ihx
    obtain ⟨v₂, C₂, hC₂, hm₂, hhom₂, happ₂⟩ := ihy
    obtain ⟨c, hc0, hc⟩ := densityEval_mul_approx v₁ v₂
    set B₂ : ℝ := ∑ F ∈ v₂.support, |v₂ F| with hB₂
    have hB₂0 : 0 ≤ B₂ := Finset.sum_nonneg (fun _ _ => abs_nonneg _)
    refine ⟨v₁ * v₂, ‖x‖ * C₂ + B₂ * C₁ + c, by positivity, ?_, ?_, ?_⟩
    · show Measurable fun a => x a * y a
      exact hm₁.mul hm₂
    · intro φ
      show x φ.coe * y φ.coe = φ ⟦v₁ * v₂⟧
      rw [mul_quot, PositiveHom.map_mul, hhom₁ φ, hhom₂ φ]
    · intro n X hn
      show |(x _ * y _) - densityEval (v₁ * v₂) ⟨n, X⟩|
        ≤ (‖x‖ * C₂ + B₂ * C₁ + c) / n
      set aX := funFromFlagWithSizeToFlagDensitySpace σ n X with haX
      have key : x aX * y aX - densityEval (v₁ * v₂) ⟨n, X⟩
          = x aX * (y aX - densityEval v₂ ⟨n, X⟩)
            + densityEval v₂ ⟨n, X⟩ * (x aX - densityEval v₁ ⟨n, X⟩)
            + (densityEval v₁ ⟨n, X⟩ * densityEval v₂ ⟨n, X⟩
                - densityEval (v₁ * v₂) ⟨n, X⟩) := by ring
      rw [key]
      have h1 : |x aX * (y aX - densityEval v₂ ⟨n, X⟩)| ≤ ‖x‖ * (C₂ / n) := by
        rw [abs_mul]
        apply mul_le_mul ?_ (happ₂ n X hn) (abs_nonneg _) (norm_nonneg x)
        have := x.norm_coe_le_norm aX
        rwa [Real.norm_eq_abs] at this
      have h2 : |densityEval v₂ ⟨n, X⟩ * (x aX - densityEval v₁ ⟨n, X⟩)| ≤ B₂ * (C₁ / n) := by
        rw [abs_mul]
        exact mul_le_mul (abs_densityEval_le v₂ _) (happ₁ n X hn) (abs_nonneg _) hB₂0
      have h3 : |densityEval v₁ ⟨n, X⟩ * densityEval v₂ ⟨n, X⟩
          - densityEval (v₁ * v₂) ⟨n, X⟩| ≤ c / n := by
        rw [abs_sub_comm]
        exact hc n X hn
      have hstep : |x aX * (y aX - densityEval v₂ ⟨n, X⟩)
            + densityEval v₂ ⟨n, X⟩ * (x aX - densityEval v₁ ⟨n, X⟩)
            + (densityEval v₁ ⟨n, X⟩ * densityEval v₂ ⟨n, X⟩
                - densityEval (v₁ * v₂) ⟨n, X⟩)|
          ≤ |x aX * (y aX - densityEval v₂ ⟨n, X⟩)|
            + |densityEval v₂ ⟨n, X⟩ * (x aX - densityEval v₁ ⟨n, X⟩)|
            + |densityEval v₁ ⟨n, X⟩ * densityEval v₂ ⟨n, X⟩
                - densityEval (v₁ * v₂) ⟨n, X⟩| := by
        refine le_trans (abs_add_le _ _) ?_
        exact add_le_add (abs_add_le _ _) (le_refl _)
      refine le_trans hstep ?_
      have heq : ‖x‖ * (C₂ / n) + B₂ * (C₁ / n) + c / n
          = (‖x‖ * C₂ + B₂ * C₁ + c) / n := by
        field_simp
      exact le_of_le_of_eq (add_le_add (add_le_add h1 h2) h3) heq

/-! ## Moment convergence: the role of Razborov's Theorem 3.12 -/

/-- Along any convergent flag sequence, the empirical integrals of a linear
evaluation converge to the normalized downward value. -/
theorem tendsto_integral_densityEvalFun
    {s : FlagSeq ∅ₜ} {φ₀ : PositiveHom ∅ₜ} (hσ : φ₀ ⟨σ⟩₀ > 0)
    (hs_conv : ConvergesTo s φ₀.coe)
    (hs_den : ∀ n, flagDensity₁ σ.toEmptyTypeFlag (s n).2 > 0)
    (v : FlagVector σ)
    : Tendsto (fun n => ∫ a, densityEvalFun v a ∂((s n).toMeasure (hs_den n))) atTop
        (𝓝 (φ₀ ⟦⟦v⟧⟧₀ / φ₀ ⟦(1 : FlagAlgebra σ)⟧₀))
  := by
  have hint : ∀ (n : ℕ) (F : FinFlag σ),
      Integrable (fun a : FlagDensitySpace σ => v F * a F) ((s n).toMeasure (hs_den n)) := by
    intro n F
    apply integrable_of_bounded ((flagDensitySpace_eval_measurable F).const_mul _) |v F|
    intro a
    rw [abs_mul]
    calc |v F| * |a F| ≤ |v F| * 1 :=
          mul_le_mul_of_nonneg_left (flagDensitySpace_abs_le_one a F) (abs_nonneg _)
      _ = |v F| := mul_one _
  have heq : ∀ n, (∫ a, densityEvalFun v a ∂((s n).toMeasure (hs_den n)))
      = ∑ F ∈ v.support, v F * ∫ a, (a F : ℝ) ∂((s n).toMeasure (hs_den n)) := by
    intro n
    dsimp only [densityEvalFun]
    rw [integral_finset_sum _ (fun F _ => hint n F)]
    apply Finset.sum_congr rfl
    intro F _
    exact integral_const_mul _ _
  rw [tendsto_congr heq]
  have htarget : φ₀ ⟦⟦v⟧⟧₀ / φ₀ ⟦(1 : FlagAlgebra σ)⟧₀
      = ∑ F ∈ v.support, v F * (φ₀ ⟦⟦basisVector F⟧⟧₀ / φ₀ ⟦(1 : FlagAlgebra σ)⟧₀) := by
    conv_lhs => rw [flagVector_eq_sum_basisVector v]
    rw [sum_quot, downward_sum, PositiveHom.map_sum, Finset.sum_div]
    apply Finset.sum_congr rfl
    intro F _
    rw [smul_quot, downward_smul, PositiveHom.map_smul, mul_div]
  rw [htarget]
  apply tendsto_finset_sum
  intro F _
  exact (tendsto_integral_flagDensitySpace_of_converge_flagSeq hσ hs_conv hs_den F).const_mul (v F)

/-- **Moment convergence** (the working form of Razborov's Theorem 3.12): for
any element of the coordinate algebra represented by a vector `v` (with the
`C/n` bound of `coordAlgebra_approx`), the empirical integrals along *any*
convergent flag sequence tend to the `ℙ[φ₀]`-moment of `v`. -/
theorem tendsto_integral_coordAlgebra (hn₀ : 1 ≤ n₀)
    {s : FlagSeq ∅ₜ} {φ₀ : PositiveHom ∅ₜ} (hσ : φ₀ ⟨σ⟩₀ > 0)
    (hs_conv : ConvergesTo s φ₀.coe)
    (hs_den : ∀ n, flagDensity₁ σ.toEmptyTypeFlag (s n).2 > 0)
    {g : C(FlagDensitySpace σ, ℝ)} (hgm : Measurable ⇑g)
    {v : FlagVector σ} {C : ℝ} (hC : 0 ≤ C)
    (happ : ∀ (n : ℕ) (X : FlagWithSize σ n), 1 ≤ n →
      |g (funFromFlagWithSizeToFlagDensitySpace σ n X) - densityEval v ⟨n, X⟩| ≤ C / n)
    : Tendsto (fun n => ∫ a, g a ∂((s n).toMeasure (hs_den n))) atTop
        (𝓝 (φ₀ ⟦⟦v⟧⟧₀ / φ₀ ⟦(1 : FlagAlgebra σ)⟧₀))
  := by
  have hsize : ∀ n, 1 ≤ (s n).1 := by
    intro n
    have h1 := flagDensity_le_card (hs_den n)
    simp only [Fintype.card_fin] at h1
    omega
  have hg_int : ∀ n, Integrable ⇑g ((s n).toMeasure (hs_den n)) := by
    intro n
    apply integrable_of_bounded hgm ‖g‖
    intro a
    have := g.norm_coe_le_norm a
    rwa [Real.norm_eq_abs] at this
  have hv_int : ∀ n, Integrable (densityEvalFun v) ((s n).toMeasure (hs_den n)) := by
    intro n
    apply integrable_of_bounded (measurable_densityEvalFun v) (∑ F ∈ v.support, |v F|)
    exact abs_densityEvalFun_le v
  have hlin := tendsto_integral_densityEvalFun hσ hs_conv hs_den v
  have hdiff : Tendsto (fun n => (∫ a, g a ∂((s n).toMeasure (hs_den n)))
      - ∫ a, densityEvalFun v a ∂((s n).toMeasure (hs_den n))) atTop (𝓝 0) := by
    have hbound : ∀ n, ‖(∫ a, g a ∂((s n).toMeasure (hs_den n)))
        - ∫ a, densityEvalFun v a ∂((s n).toMeasure (hs_den n))‖ ≤ C / ((s n).1 : ℝ) := by
      intro n
      rw [Real.norm_eq_abs]
      apply FinFlag.abs_integral_toMeasure_sub_le (s n) (hs_den n) _ _ (hg_int n) (hv_int n)
        (by positivity)
      intro F' _
      rw [densityEvalFun_emp]
      exact happ (s n).1 F' (hsize n)
    refine squeeze_zero_norm hbound ?_
    · have hmono : ∀ n, C / ((s n).1 : ℝ) ≤ C / (max 1 n : ℕ) := by
        intro n
        apply div_le_div_of_nonneg_left hC ?_ ?_
        · have := hsize n
          positivity
        · have h1 : (max 1 n : ℕ) ≤ (s n).1 := by
            rcases Nat.eq_zero_or_pos n with rfl | hn
            · simpa using hsize 0
            · have h2 : n ≤ (s n).1 := hs_conv.1.id_le n
              omega
          exact_mod_cast h1
      apply squeeze_zero
      · intro n
        have := hsize n
        positivity
      · exact hmono
      · have : Tendsto (fun n : ℕ => C / ((max 1 n : ℕ) : ℝ)) atTop (𝓝 0) := by
          apply Tendsto.comp (tendsto_const_div_atTop_nhds_zero_nat C)
          apply tendsto_atTop_atTop.mpr
          intro b
          exact ⟨b, fun n hn => le_trans hn (le_max_right 1 n)⟩
        exact this
  have hfin : (fun n => ∫ a, g a ∂((s n).toMeasure (hs_den n)))
      = fun n => (∫ a, densityEvalFun v a ∂((s n).toMeasure (hs_den n)))
        + ((∫ a, g a ∂((s n).toMeasure (hs_den n)))
          - ∫ a, densityEvalFun v a ∂((s n).toMeasure (hs_den n))) := by
    funext n
    ring
  rw [hfin]
  simpa using hlin.add hdiff

/-- The `ℙ[φ₀]`-integral of a coordinate-algebra element represented by `v`
is the `v`-moment of the spec. -/
theorem integral_probMeasure_coordAlgebra
    {φ₀ : PositiveHom ∅ₜ} (hσ : φ₀ ⟨σ⟩₀ > 0)
    {g : C(FlagDensitySpace σ, ℝ)} {v : FlagVector σ}
    (hhom : ∀ φ : PositiveHom σ, g φ.coe = φ ⟦v⟧)
    : ∫ φ, g (φ : PositiveHomSpace σ).val
        ∂(probMeasure_extend_emptyType_positiveHom φ₀ hσ)
      = φ₀ ⟦⟦v⟧⟧₀ / φ₀ ⟦(1 : FlagAlgebra σ)⟧₀
  := by
  rw [← probMeasure_extend_emptyType_positiveHom_spec hσ ⟦v⟧]
  apply integral_congr_ae
  apply ae_of_all
  intro φ
  have h := Classical.choose_spec φ.property
  show g φ.val = (PositiveHomSpace.toPosHom φ) ⟦v⟧
  rw [show φ.val = (PositiveHomSpace.toPosHom φ).coe from h.symm, hhom]

end Differential
end FlagAlgebras
